//! Wire-format sample tests: run synthetic terminal byte streams through the
//! parser and transformer, asserting structure-level and byte-level results.
//!
//! Fixture provenance (see tests/fixtures/README.md): the streams are
//! generated by `scripts/gen_fixtures.py` and reproduce the wire format that
//! real kitty-protocol emitters (kitty +kitten icat, matplotlib kitty
//! backends, notcurses) put on the wire — 4096-byte base64 chunking, image
//! ids, delete commands — interleaved with ordinary shell/CSI output. They
//! are not captures of live terminal sessions.

use std::path::PathBuf;

use pixmux::parser::{Event, StreamParser};
use pixmux::transform::{Target, Transformer};

fn fixture(name: &str) -> Vec<u8> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("cannot read fixture {path:?}: {e}"))
}

#[test]
fn icat_stream_parses_into_expected_events() {
    let data = fixture("icat_chunked.bin");
    let mut parser = StreamParser::new();
    let mut events = parser.feed(&data);
    events.extend(parser.finish());

    let graphics: Vec<_> = events
        .iter()
        .filter_map(|e| match e {
            Event::Graphics { cmd, .. } => Some(cmd),
            _ => None,
        })
        .collect();
    // The stream contains one 3-chunk transmission + one delete command.
    assert_eq!(graphics.len(), 4, "expected 4 graphics commands");
    assert_eq!(graphics[0].action(), "T");
    assert_eq!(graphics[0].format(), 100);
    assert!(graphics[0].more_chunks());
    assert!(graphics[1].more_chunks());
    assert!(!graphics[2].more_chunks());
    assert_eq!(graphics[3].action(), "d");

    // No plain bytes are lost: total passthrough equals the original stream
    // minus the graphics sequences.
    let plain: usize = events
        .iter()
        .map(|e| match e {
            Event::Passthrough(b) => b.len(),
            _ => 0,
        })
        .sum();
    let seq: usize = events
        .iter()
        .map(|e| match e {
            Event::Graphics { raw, .. } => raw.len(),
            _ => 0,
        })
        .sum();
    assert_eq!(plain + seq, data.len());
}

#[test]
fn icat_stream_tmux_translation_matches_golden() {
    let data = fixture("icat_chunked.bin");
    let golden = fixture("icat_chunked.tmux.golden");
    let mut t = Transformer::new(Target::Tmux);
    let mut out = t.feed(&data);
    out.extend(t.finish());
    assert_eq!(
        out, golden,
        "tmux translation drifted from the cross-checked golden output"
    );
    assert_eq!(t.stats().graphics_commands, 4);
    assert_eq!(t.stats().translated, 4);
}

#[test]
fn icat_stream_survives_arbitrary_split_points() {
    let data = fixture("icat_chunked.bin");
    // Reference output computed on the unsplit stream.
    let mut whole = Transformer::new(Target::Tmux);
    let mut expected = whole.feed(&data);
    expected.extend(whole.finish());

    for split in [1usize, 2, 3, 7, 100, 4095, 4096, 4097] {
        let mut t = Transformer::new(Target::Tmux);
        let mut out = Vec::new();
        for chunk in data.chunks(split) {
            out.extend(t.feed(chunk));
        }
        out.extend(t.finish());
        assert_eq!(out, expected, "split size {split} changed the output");
    }
}

#[test]
fn png_stream_transcodes_to_sixel_for_zellij() {
    let data = fixture("icat_chunked.bin");
    let mut t = Transformer::new(Target::Zellij);
    let mut out = t.feed(&data);
    out.extend(t.finish());
    let s = String::from_utf8_lossy(&out);
    assert!(s.contains("\u{1b}P0;1;0q"), "sixel header missing");
    assert!(
        !s.contains("\u{1b}_G"),
        "kitty APC leaked into zellij output"
    );
    assert_eq!(t.stats().images_decoded, 1);
    // Shell prompt text from the stream is preserved.
    assert!(s.contains("$ "));
}

#[test]
fn plain_vim_session_stream_is_untouched() {
    let data = fixture("plain_vim_session.bin");
    for target in [Target::Tmux, Target::Zellij, Target::Strip, Target::None] {
        let mut t = Transformer::new(target);
        let mut out = t.feed(&data);
        out.extend(t.finish());
        assert_eq!(out, data, "target {target} altered a graphics-free stream");
        assert_eq!(t.stats().graphics_commands, 0);
    }
}
